# Generated by Django 4.2.4 on 2023-10-10 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0006_song_like_count_userlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='liked_by_users',
            field=models.ManyToManyField(related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
